-- 创建数据库app-sso
CREATE DATABASE `app-sso` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci';

-- 创建用户信息表
CREATE TABLE `T_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `USERNAME` varchar(255) DEFAULT NULL COMMENT '账号',
  `PASSWORD` varchar(255) DEFAULT NULL COMMENT '密码',
  `EMAIL` varchar(255) DEFAULT NULL COMMENT '邮箱',
  `MOBILE` varchar(64) DEFAULT NULL COMMENT '手机号',
  `NICKNAME` varchar(255) DEFAULT NULL COMMENT '昵称',
  `GENDER` varchar(32) DEFAULT NULL COMMENT '性别',
  `BIRTHDAY` varchar(32) DEFAULT NULL COMMENT '生日',
  `ID_NAME` varchar(64) DEFAULT NULL COMMENT '真实姓名',
  `ID_CARD_TYPE` varchar(32) DEFAULT NULL COMMENT '证件类型',
  `ID_CARD` varchar(255) DEFAULT NULL COMMENT '证件号',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CREATE_USER` varchar(255) DEFAULT NULL COMMENT '创建人',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  `UPDATE_USER` varchar(255) DEFAULT NULL COMMENT '更新人',
  `PERMIT_ROLE` varchar(255) DEFAULT NULL COMMENT '权限角色',
  `VALID` int(11) DEFAULT NULL COMMENT '是否有效',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=100001 DEFAULT CHARSET=utf8mb4;
